hairyhenderson/go-fsimpl

- README.md
- url_schemes.md
While it may be useful for gomplate to support this, I don't think it's that useful for any general-purpose uses... Removing it from docs!
> Remove mention of 'env:' scheme

- filefs/file.go
- filefs/file_test.go
UNCs weren't supported before by `filefs`. This should fix that!
> filefs: Properly support Windows UNCs

- .golangci.yml
- internal/billyadapter/frozentime.go
- internal/types.go
golint is archived in favour of revive
> Replace golint with revive

- README.md
- autofs/lookup.go
- awssmfs/awssm.go
- awssmfs/awssm_test.go
- awssmfs/fake_client_test.go
- awssmfs/types.go
- blobfs/blob.go
- extensions.go
- go.mod
- go.sum
- internal/billyadapter/btofs.go
- internal/path.go
- internal/types.go
- url_schemes.md
- vaultfs/vault.go
Fixes #6 
Support for AWS SM filesystem, with the `aws+sm` URL scheme.
Because this is effectively a flat namespace, I had to infer directory structure (using `/` as path separator in the secret name, as seems to be the recommendation in the AWS docs). A side-effect is that you can either get a filesystem rooted on secrets that start with `/`, or not. That means if a SM store has two secrets `/foo` and `bar`, you can't have a filesystem where both will be accessible. I think in practice this may not be a big deal, as I expect Secrets Manager users will likely use either a `/`-rooted convention, or not, but not both.
> Add AWS Secrets Manager FS

- gitfs/auth.go
- gitfs/auth_test.go
- gitfs/doc.go
- gitfs/example_test.go
- gitfs/git.go
- gitfs/git_test.go
- internal/tests/integration/gitfs_test.go
Currently authentication in `gitfs` requires environment variables, which can make things difficult when writing code that may not have access to the environment, or when using `gitfs` concurrently against different repos.
This solves the problem by adding a `WithAuthenticator` wrapper function to compose a `gitfs.FS` with an authentication method. This is similar to the `vaultfs.WithAuthMethod` function, though in this case it needs to work slightly differently due to how the underlying `go-git` module works. I'm not that happy with naming, but we're pre-1.0 still, so that can change.
The previous behaviour is preserved by the `gitfs.AutoAuthenticator`, which will infer credentials from the URL or environment depending on the URL scheme.
Signed-off-by: Dave Henderson …
> gitfs: support setting explicit auth methods

- awssmfs/doc.go
- blobfs/doc.go
> Improve some package docs

- mux.go
- mux_test.go
Convenience function to help primarily with testing in consuming modules
> Add WrappedFSProvider function

- mux.go
- mux_test.go
Seems like a bit of a no-brainer that `FSMux` should also implement `FSProvider`... Might make it slightly easier to consume!
> FSMux now implements FSProvider

- go.mod
- go.sum
Fixes #64, which was broken accidentally during some routine dependency updates (#92).
This time I've separated the `require` line and added an explanatory comment which _should_ prevent this from happening again!
I understand that the eventual goal in https://github.com/Azure/azure-pipeline-go/issues/31 is to simply remove the dependency on the problematic package. Once that happens we can simply delete the line.
> Downgrade github.com/mattn/go-ieproxy to v0.0.1 again

- examples/fscli/main.go
- examples/fscli/main_test.go
Adds a new `fscli` command that can be built and used for playing with go-fsimpl, or just as an example of how to use it.
> Example cli for testing

- filefs/file_test.go
- filefs/file_windows_test.go
Sometimes I see failures like this when running `TestFileFS` on Windows:
```
--- FAIL: TestFileFS (0.06s)
file_test.go:31: 
Error Trace:	D:\a\go-fsimpl\go-fsimpl\filefs\file_test.go:31
Error:      	Received unexpected error:
TestFS found errors:
sub: mismatch:
entry.Info() = sub IsDir=true Mode=drwxrwxrwx Size=0 ModTime=2022-08-21 16:02:47.0513102 +0000 GMT
file.Stat() = sub IsDir=true Mode=drwxrwxrwx Size=0 ModTime=2022-08-21 16:02:47.0518252 +0000 GMT
Test:       	TestFileFS
```
I'm not sure _why_ there are slightly-different ModTimes for the same directory, but in concept setting an explicit ModTime may help? 🤷‍♂️
> Attempt to make filesystem test less flakey on Windows

- vaultfs/vault_test.go
If the environment variable VAULT_ADDR is set, as is quite likely with a regular vault user, the TestVaultConfig test will fail with
Error:          Not equal:
expected: "https://127.0.0.1:8200"
actual  : "<VAULT_ADDR>"
This fixes that problem.
> Allow vault test to pass if VAULT_ADDR set

- README.md
- internal/tests/integration/gitfs_test.go
Some notes added on how to get the tests to pass.
Changed some of the gomplate temporary paths to gofsimpl paths instead.
git init with recent git creates a `main` branch not a `master` branch. This makes the test fail. As a simple workaround I've made sure we're on `master`.
> A few test tidy ups, including working with modern git

- internal/tests/integration/vaultfs_test.go
- vaultfs/doc.go
- vaultfs/vault.go
- vaultfs/vault_test.go
Fixes #24 
This adds support for the [K/V v2](https://www.vaultproject.io/docs/secrets/kv/kv-v2) secrets mounts. It can be used in exactly the same way that K/V v1 mounts are used (same URL scheme, etc). The one difference is that a `?version=` query parameter can be sent to request previous secret versions.
In this implementation, a check is made prior to accessing the mount to find out what version of the `kv` engine is in use. Currently this is done on every access, doubling the number of requests. In future it may be useful to add some caching to improve performance - _however_ because it is possible to upgrade a kv-v1 mount to kv-v2 at runtime, this will be a bit more complex to get right.
> vaultfs: Support K/V v2 secret engine

- .golangci.yml
- awssmfs/awssm.go
- awssmfs/fake_client_test.go
- awssmpfs/awssmp.go
- awssmpfs/fake_client_test.go
- go.mod
- go.sum
Supersedes https://github.com/hairyhenderson/go-fsimpl/pull/154 and https://github.com/hairyhenderson/go-fsimpl/pull/157
A few parameters in the SSM and SM SDKs were concrete types where they were intended to be pointers. This was fixed in recent versions.
> Upgrade AWS SDK deps and fix API breakage

- extensions.go
- extensions_test.go
This wasn't really a bug, it was just surprising behaviour. When using `fsimpl.ContentType`, I would _expect_ it to fall back to guessing based on file extension when `fi` has a `ContentType` method that returns an empty string.
This fixes that behaviour.
> fix: fsimpl.ContentType should fallback to extension-guessing

- internal/tests/integration/vaultfs_test.go
> Temporarily support AppID auth method while vaultfs.AuthMethod is still supported

- .github/workflows/build.yml
- .gitignore
- Makefile
Adds a `fscli-build` job to attempt to build the `fscli` binary (from `./examples/fscli`), which should expose bugs involving CGO (like what happened in #64).
Also adds a `release` make target - I'll be releasing v0.1.0 soon!
> build fscli binary in CI

- gitfs/git.go
- gitfs/git_test.go
Somehow when I fixed https://github.com/hairyhenderson/gomplate/issues/1049 in gomplate, I forgot to backport that fix to go-fsimpl! This does just that...
> gitfs: Support non-master default branches

- Makefile
- gitfs/git_test.go
- go.mod
- go.sum
- internal/tests/integration/gitfs_test.go
Related to https://github.com/hairyhenderson/gomplate/pull/1916
`gitfs` likely suffers from the same bug - this flips to a fork of go-git that has the fix cherry-picked. I'll switch back once the upstream PR is merged.
> Fix gitfs Windows-specific bugs

- awssmfs/awssm.go
- awssmpfs/awssmp.go
- blobfs/blob.go
- blobfs/blob_test.go
- consulfs/consul.go
- consulfs/consul_test.go
- examples/fscli/main_test.go
- httpfs/http.go
- internal/types.go
- vaultfs/vault.go
- vaultfs/vault_test.go
Found this during #472 - before:
```console
$ bin/fscli_darwin-amd64 -base-url=aws+imds://127.0.0.1:1338/meta-data/network ls
d---------  0001-01-01 00:00 interfaces
```
note the file permissions make the directory appear to be non-readable, while in reality it is.
After:
```console
$ bin/fscli_darwin-amd64 -base-url=aws+imds://127.0.0.1:1338/meta-data/network ls
dr-xr-xr-x  0001-01-01 00:00 interfaces
```
Files are also corrected to be marked read-only (`r--r--r--`/`0o444`).
> Correct reported file permissions to be read-only

- vaultfs/auth.go
- vaultfs/vault.go
- vaultfs/vault_test.go
- vaultfs/vaultauth/auth.go
- vaultfs/vaultauth/env.go
- vaultfs/vaultauth/env_test.go
- vaultfs/vaultauth/token.go
During https://github.com/hairyhenderson/gomplate/pull/1336 I realized that the `vaultauth.EnvAuthMethod` causes tokens to be revoked, when they shouldn't be, because it wasn't implementing the `authLogouter` interface.
I've fixed this up, and altered that interface to be able to pass a context (it's only used here, so that's safe).
This also tweaks the error handling when a GET fails and falls back to LIST - if both fail, the first error is returned since that might make a bit more sense.
This also exports `vaultauth.CompositeAuthMethod` for easier auth method composition.
> vaultfs: auth improvements

- awsimdsfs/awsimdsfs.go
- awssmfs/awssm.go
- awssmpfs/awssmp.go
- blobfs/blob.go
- consulfs/consul.go
- gitfs/git.go
- httpfs/http.go
- vaultfs/vault.go
If I call `WithHTTPClient(nil)` the client will be set to nil, rather than falling back to the default client which was originally set. This fixes that!
> Handle possibility of nil context, clients, or headers

- .golangci.yml
- awssmpfs/awssmp.go
- consulfs/consul.go
- gitfs/auth.go
- gitfs/git.go
- gitfs/git_test.go
- go.mod
- vaultfs/auth.go
- vaultfs/vault.go
- vaultfs/vaultauth/github.go
Applying recommendations from the `perfsprint` linter - for example, `fmt.Errorf("...")` is about 200x slower than `errors.New("...")`!
> fix(perf): Replace slower fmt.Sprint(f) calls with faster alternatives

- awssmfs/awssm.go
- awssmpfs/awssmp.go
EndpointResolver is deprecated, using new API. Also, endpoint overriding support was missing in `awssmfs` so I added that too.
> fix(aws*fs): Use BaseEndpoint for overriding endpoints

- consulfs/consul.go
- consulfs/consul_test.go
- httpfs/http.go
- httpfs/http_test.go
- internal/url.go
- internal/url_test.go
- vaultfs/vault.go
- vaultfs/vault_test.go
Fixes a bug where query parameters on the base URL in https and consults weren't properly being used by file URLs.
This behaviour was already present on vaultfs, so I've just reused the same code.
> fix(httpfs/consulfs): base URL query parameters weren't preserved

- .github/workflows/build.yml
- Makefile
- go.mod
- internal/tests/integration/consulfs_test.go
Related to https://github.com/hairyhenderson/gomplate/issues/2121 - there are some alignment bugs in go-fsimpl that went unnoticed. Testing on a 32-bit architecture in CI should help!
> ci: Run tests on 32-bit (386) as well

- internal/tests/fakevault/fakevault.go
- internal/tests/integration/vaultfs_test.go
- vaultfs/auth_test.go
- vaultfs/vault.go
- vaultfs/vault_test.go
- vaultfs/vaultauth/env_test.go
- vaultfs/vaultauth/github_test.go
Fixes #730 
- now caches the matching mount from the `sys/internal/ui/mounts` in the file
- uses the KVv2 client directly instead of making a raw request and munging the path
> fix(vaultfs): Support KVv2 mounts that contain slashes

- autofs/lookup.go
- vaultfs/vault.go
- vaultfs/vault_test.go
Missed a bug in #738 - Stat wasn't working properly when directly listing the mount endpoint.
Also a bit of refactoring to keep things easier to read...
> fix(vaultfs): bug when Stat builds mount info from #738

- awssmfs/awssm_test.go
- blobfs/blob.go
- blobfs/blob_test.go
- blobfs/s3blob.go
- blobfs/s3opener.go
- go.mod
- url_schemes.md
Switches to AWS SDK v2 for the S3 support in `blobfs`.
This changes somewhat the query parameters recognized in URLs, which have been updated in `url_schemes.md`.
In addition to still supporting the undocumented `AWS_ANON` env var, this adds support for an `anonymous=true` query parameter to remove the need to set environment variables. That may be removed if https://github.com/google/go-cloud/issues/3512 is fulfilled with a different query parameter, so it's documented as experimental.
> feat(blobfs): Use AWS SDK v2 for blobfs

- awssmfs/awssm.go
- awssmpfs/awssmp.go
- blobfs/blob.go
- blobfs/s3opener.go
- internal/types.go
In the original v2 aws-sdk-go, it wasn't necessary to set an AWS region, but with v2, a region is always required (at least, for most APIs). This can either be done with environment variables (`AWS_REGION`, for example), or by a shared config. On EC2, however, it's customary to fall back to the instance metadata service (IMDS).
This is necessary for https://github.com/hairyhenderson/gomplate/issues/2180, for example.
> fix(aws): Get region from IMDS when missing for awssmfs, awssmpfs, and blobfs (s3://)

- .github/workflows/benchmark.yml
The benchmark workflow was failing on Dependabot PRs with a "Resource not accessible by integration" error when trying to post benchmark results. This was because Dependabot PRs have more restricted token permissions by default.
Fixes the failure that happened in #990
> fix(ci): add explicit permissions to benchmark workflow

- .github/workflows/benchmark.yml
I think this'll fix the failures in `main` since #1000
> fix(ci): need contents write perm for benchmark workflow
